name: First CI Workflow


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

        # actions/checkout@v4 is a GitHub Action that checks out your repository under $GITHUB_WORKSPACE, so your workflow can access it. This action is necessary for any workflow that needs to access the code in the repository.
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Specify the Python version you want to use
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r session_6_CI/requirements.txt
          
      - name: Run tests
        run: |
          pytest

    